### ISSUE TITLE
Ошибка Uncaught exception 'GuzzleHttp\Exception\ConnectException' 

### ISSUE THREAD

**Issue by Pankrashingo** [nixsolutions/yandex-php-library#142]
Здравствуйте. После последнего локального обновления guzzlehttp/promises с версии 1.0.3 до версии 1.1.0 и guzzlehttp/psr7 с 1.2.2 до 1.2.3 появилась ошибка:

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 35: Unknown SSL protocol error in connection to api-metrika.yandex.ru:443 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\OpenServer\domains\smpzmaster.ru\engine\functions\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186 Stack trace: #0 C:\OpenServer\domains\smpzmaster.ru\engine\functions\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\OpenServer\domains\smpzmaster.ru\engine\functions\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\OpenServer\domains\smpzmaster.ru\engine\functions\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Ob in C:\OpenServer\domains\smpzmaster.ru\engine\functions\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 186

Подскажите как быть?

**Comment by naxel** [comment]
Здравствуйте. 
Напишите пожалуйста версию PHP, версию CURL (и другую информацию о нем, которую можно получить в phpinfo() ) и запрос, который пытаетесь выполнить.
В https://github.com/guzzle/guzzle/issues/1364 описываеться похожая ошибка, попробуйте  указать CURLOPT_SSLVERSION в CURL_SSLVERSION_TLSv1_2, к примеру так:
``` php
$response = $this->sendRequest(
    'GET',
    $this->getServiceUrl($resource, $params),
    [
        'curl' => [CURLOPT_SSLVERSION => CURL_SSLVERSION_TLSv1_2]
    ]
);
```

**Comment by Pankrashingo** [comment]
Версия PHP 5.6.12
[Скриншот информации о cURL](http://take.ms/qFSkL)
[Скриншот кода, при вызове функции на 45 строке возникает ошибка](http://take.ms/jeOjE)

Добавление указанных вами строк сюда `vendor/nixsolutions/yandex-php-library/src/Yandex/Metrica/MetricaClient.php:120` не помогло

**Comment by naxel** [comment]
Баг воспроизвелся при прогонке тестов (но на другой АПИ), потом снова пропал 
![http://joxi.ru/Y2Lk3RwinbwYwm](http://dl1.joxi.net/drive/0007/0543/471583/160311/b363bbf32e.jpg)

**Comment by Pankrashingo** [comment]
Пока нет никаких советов по решению проблемы? 
Ошибка все так же осталась, причина в guzzlehttp само собой...

**Comment by Pankrashingo** [comment]
Еще экспериментировали - [Исходный код](http://take.ms/s6eOV)
Несколько раз подряд обновляя страницу выводится:
- то [результат](http://take.ms/yIfl2);
- то [ошибка](http://take.ms/Axx03).

Без какой-либо последовательности. Может несколько раз подряд ошибка, или наоборот. Может через раз.

**Comment by Pankrashingo** [comment]
Так же была найдена следующая проблема с получением данных (на версии библиотеки 0.4.0, где проблемы с guzzle нет):
На примере выдачи информации на [сайте ](http://take.ms/gnLTe). 
При удачном получении данных диаграмма выглядит [вот так](http://take.ms/JMjRS).
Проблема повторяется довольно часто, очень схоже с частотой ошибки, описанной выше.
